=== aezzaididam1/LMGI/public_html/UT02/EJ/retrieve.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="CrossSectionalData" type="CrossSectionalDataType"/>

  <xs:complexType name="CrossSectionalDataType">
    <xs:sequence>
      <xs:element type="HeaderType" name="Header"/>
      <xs:element type="DataSetType" name="DataSet"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="HeaderType">
    <xs:sequence>
      <xs:element type="tipoID" name="ID"/>
      <xs:element type="xs:boolean" name="Test"/>
      <xs:element type="NameType" name="Name"/>
      <xs:element type="xs:date" name="Prepared"/>
      <xs:element type="SenderType" name="Sender"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipoID">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]{4,5}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="NameType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="lang" use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="SenderType">
    <xs:sequence>
      <xs:element type="NameType" name="Name"/>
      <xs:element type="ContactType" name="Contact"/>
    </xs:sequence>
    <xs:attribute type="tipoID" name="id"/>
  </xs:complexType>

  <xs:complexType name="ContactType">
    <xs:sequence>
      <xs:element type="NameType" name="Name"/>
      <xs:element type="tipoEmail" name="Email"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="tipoEmail">
    <xs:restriction base="xs:string">
      <xs:pattern value=".{1,64}@.{1,59}[.][a-z]{2,3}"/>
    </xs:restriction>
  </xs:simpleType>

  <!--      -->

  <xs:complexType name="DataSetType">
    <xs:sequence>
      <xs:element type="GroupType" name="Group"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="GroupType">
    <xs:sequence>
      <xs:element type="SectionType" name="Section" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute type="tipoLetra" name="AUCTION_STATUS"/>
    <xs:attribute type="tipoLetra" name="AVAILABILITY"/>
    <xs:attribute type="tipoLetra" name="DISCLAIMER"/>
    <xs:attribute type="xs:dateTime" name="LAST_UPDATED"/>
    <xs:attribute type="tipoLetra" name="OBS_STATUS"/>
    <xs:attribute type="xs:string" name="OPERATION_ID"/>
    <xs:attribute type="xs:string" name="TIME_FORMAT"/>
  </xs:complexType>

  <xs:simpleType name="tipoLetra">
    <xs:restriction base="xs:string">
      <xs:pattern value="[A-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="SectionType">
    <xs:sequence>
      <xs:element type="InSectType" name="OFFERING_AMOUNT" minOccurs="0"/>
      <xs:element type="InSectType" name="MAX_AWARD_AMOUNT" minOccurs="0"/>
      <xs:element type="InSectType" name="MIN_FEE_RATE" minOccurs="0"/>
      <xs:element type="InSectType" name="SECURITY_AMOUNT_AVAILABLE_FOR_LOAN" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="InSectType" name="PAR_ACCEPTED" minOccurs="0"/>
      <xs:element type="InSectType" name="PAR_SUBMITTED" minOccurs="0"/>
      <xs:element type="InSectType" name="BID_TO_COVER" minOccurs="0"/>
      <xs:element type="InSectType" name="STOP_OUT_RATE" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="AUCTION_CLOSE_TIME"/>
    <xs:attribute type="xs:string" name="AUCTION_COLLATERAL_TYPE"/>
    <xs:attribute type="xs:string" name="AUCTION_START_TIME"/>
    <xs:attribute type="xs:string" name="MATURITY_DATE"/>
    <xs:attribute type="xs:string" name="SECTION_TYPE"/>
    <xs:attribute type="xs:string" name="SETTLEMENT_DATE"/>
    <xs:attribute type="xs:string" name="TERM"/>
    <xs:attribute type="xs:string" name="TIME"/>
  </xs:complexType>

  <xs:complexType name="InSectType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="DECIMALS"/>
        <xs:attribute type="xs:string" name="CURRENCY_UNIT"/>
        <xs:attribute type="tipoLetra" name="OBS_CONF"/>
        <xs:attribute type="tipoLetra" name="OBS_STATUS"/>
        <xs:attribute type="xs:string" name="SECURITY_DESCRIPTION"/>
        <xs:attribute type="xs:string" name="UNIT_MULT"/>
        <xs:attribute type="xs:string" name="value"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

</xs:schema>

=== aezzaididam1/LMGI/public_html/UT02/EJ/retrieve.xml
<?xml version="1.0" encoding="UTF-8"?>
<CrossSectionalData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="retrieve.xsd">
  <Header>
    <ID>TSLF</ID>
    <Test>false</Test>
    <Name lang="en">TSLDF</Name>
    <Prepared>2021-10-28</Prepared>
    <Sender id="FRBNY">
      <Name lang="en">Federal Reserve Bank of New York</Name>
      <Contact>
        <Name lang="en">Public Information Web Team</Name>
        <Email>ny.piwebteam@ny.frb.org</Email>
      </Contact>
    </Sender>
  </Header>
  <DataSet>
    <Group AUCTION_STATUS="C" AVAILABILITY="A" DISCLAIMER="G" LAST_UPDATED="2016-01-30T18:52:30-05:00" OBS_STATUS="F" OPERATION_ID="TSLF2 010710" TIME_FORMAT="PT1M">
      <Section AUCTION_CLOSE_TIME="2016-01-30T14:30:00-05:00" AUCTION_COLLATERAL_TYPE="S2" AUCTION_START_TIME="2016-01-30T14:00:00-05:00" MATURITY_DATE="2010-02-05T00:00:00-05:00" SECTION_TYPE="ANNOUNCEMENT" SETTLEMENT_DATE="2010-01-08T00:00:00-05:00" TERM="28-day" TIME="2010-01-06">
        <OFFERING_AMOUNT CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" UNIT_MULT="9" value="25.000"/>
        <MAX_AWARD_AMOUNT CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" UNIT_MULT="9" value="5.000"/>
        <MIN_FEE_RATE DECIMALS="4" OBS_CONF="F" OBS_STATUS="A" UNIT_MULT="-2" value=".2500"/>
        <SECURITY_AMOUNT_AVAILABLE_FOR_LOAN CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" SECURITY_DESCRIPTION="T 00.875 12/31/10" UNIT_MULT="6" value="4104"/>
        <SECURITY_AMOUNT_AVAILABLE_FOR_LOAN CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" SECURITY_DESCRIPTION="T 00.875 04/30/11" UNIT_MULT="6" value="3080"/>
        <SECURITY_AMOUNT_AVAILABLE_FOR_LOAN CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" SECURITY_DESCRIPTION="T 04.125 08/31/12" UNIT_MULT="6" value="3498"/>
        <SECURITY_AMOUNT_AVAILABLE_FOR_LOAN CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" SECURITY_DESCRIPTION="T 04.250 11/15/14" UNIT_MULT="6" value="1654"/>
        <SECURITY_AMOUNT_AVAILABLE_FOR_LOAN CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" SECURITY_DESCRIPTION="T 07.500 11/15/16" UNIT_MULT="6" value="5715"/>
        <SECURITY_AMOUNT_AVAILABLE_FOR_LOAN CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" SECURITY_DESCRIPTION="T 04.000 08/15/18" UNIT_MULT="6" value="6946"/>
      </Section>
      <Section AUCTION_COLLATERAL_TYPE="S2" SECTION_TYPE="RESULTS">
        <PAR_ACCEPTED CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" UNIT_MULT="6" value="0"/>
        <PAR_SUBMITTED CURRENCY_UNIT="USD" OBS_CONF="F" OBS_STATUS="A" UNIT_MULT="6" value="0"/>
        <BID_TO_COVER DECIMALS="2" OBS_CONF="F" OBS_STATUS="A" value=".00"/>
        <STOP_OUT_RATE DECIMALS="4" OBS_CONF="F" OBS_STATUS="A" value=".2500"/>
      </Section>
    </Group>
  </DataSet>
</CrossSectionalData>
