=== aezzaididam1/LMGI/public_html/UT02/A3/patrones.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"> 

    <xs:element name="patrones" type="patronesType"/>
    
    <xs:complexType name="patronesType">
        <xs:sequence>
            <xs:element name="e1" type="e1Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e2" type="e2Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e3" type="e3Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e4" type="e4Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e5" type="e5Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e6" type="e6Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e7" type="e7Type" maxOccurs="unbounded" minOccurs="0"/>
            <xs:element name="e8" type="e8Type" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="e1Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="Capítulo \d"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e2Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="Capítulo \d{1,2}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e3Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="(Capítulo [1-9]?[1-9])|(Capítulo [1-9]0)"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e4Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="Capítulo \d+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e5Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="\DZ"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e6Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="AB{2,5}C"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e7Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="RS{2,}[3-8]?"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="e8Type">
        <xs:restriction base="xs:string">
            <xs:pattern value="COD\d{3}.+"/>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== aezzaididam1/LMGI/public_html/UT02/A3/patrones.xml
<?xml version="1.0" encoding="UTF-8"?>
<patrones xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="patrones.xsd"> 
    <e1>Capítulo 0</e1>
    <e1>Capítulo 9</e1>
    <e2>Capítulo 0</e2>
    <e2>Capítulo 02</e2>
    <e2>Capítulo 99</e2>
    <!-- 
    <e3>Capítulo 0</e3>
    -->
    <!--
    <e3>Capítulo 02</e3>
    -->
    <e3>Capítulo 1</e3>
    <e3>Capítulo 10</e3>
    <e3>Capítulo 99</e3>
    <!--
    <e4>Capítulo </e4>
    -->
    <e4>Capítulo 0</e4>
    <e4>Capítulo 04</e4>
    <e4>Capítulo 100</e4>
    <!--
    <e5>0Z</e5>
    -->
    <e5>aZ</e5>
    <e5>=Z</e5>
    <!--
    <e6>ABC</e6>
    -->
    <e6>ABBC</e6>
    <e6>ABBBC</e6>
    <e6>ABBBBC</e6>
    <e6>ABBBBBC</e6>
    <!--
    <e7>RSS2</e7>
    -->
    <e7>RSS</e7>
    <e7>RSSSSSSSSSSS7</e7>
    <!--
    <e8>COD645</e8>
    -->
    <e8>COD645pera</e8>
    <e8>COD646manzana</e8>
</patrones>
